config/routes.rb
Rails.application.routes.draw do
  get 'tasks/new', to: 'tasks#new'
  get 'tasks', to: 'tasks#show'
  get 'tasks/:id', to: 'tasks#detail', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit'
  post 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @tasks = Task.all
  end

  def new # create
    @task = Task.new
  end

  def detail
    @task = Task.find(params[:id])
  end

  def create
    @tasks = Task.new(title: params[:task][:title],
                      details: params[:task][:details])
    @tasks.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(title: params[:task][:title],
                 details: params[:task][:details])
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/detail.html.erb
<h1><%= @task.title %></h1>

<%= button_to "Edit this task", edit_path %>

<p><%= @task.details %></p>
<input type="checkbox">This task is completed

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/edit.html.erb
<h1><strong>Edit Task<strong></h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>
<br>
<%= link_to "back to list", task_url %>

app/views/tasks/new.html.erb
<h1><strong>New Task<strong></h1>
<br>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

<%= link_to "back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><strong>My Tasks</strong></h1>

  <% @tasks.each do |task| %>
    <li><label><input type="checkbox">
      <%= link_to task.title, task_path(task) %>
      <%= button_to "delete", destroy_path(task),
      method: :delete %>
    </li></label>
  <% end %>

<%= link_to "+ Add a new task", tasks_new_path %>